### ISSUE TITLE
Indicate that a Stripe donation was successful

### ISSUE THREAD

**Issue by humphd** [mekkim/donatemask#101]
Spin-off from https://github.com/mekkim/donatemask/issues/99#issuecomment-1127031843.  When a Stripe donation goes through successfully, we redirect the user back to `/donate` and add `?success=true`.  We should use this info to replace the Donate form component with a different component that does the following:

- Indicates the donation was successful
- Includes some kind of "thank you" text
- Possibly includes some social media share buttons, so people can Tweet, etc. something like "I'm supporting https://donatemask.ca..." (text needs to be figured out).

**Comment by mekkim** [comment]
Thumbs up!

**Comment by Sync271** [comment]
The sharing option would be a really nice touch!
