### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by humphd** [mekkim/donatemask#105]
To better understand what is and isn't working, with respect to site traffic, requests, and donations, let's add Google Analytics.

I can do the code side, but there are some account bits that should get done by @mekkim.  Here's the background: [Google Analytics 4](https://support.google.com/analytics/answer/10089681)

Steps we need to take:

1. (@mekkim ) Create a GA4 account, see https://support.google.com/analytics/answer/9304153
2. (@humphd) Add the `gtag.js` script to the site HTML, making it configurable via env (so it doesn't run in testing)
3. (@mekkim) Give access to those people who need it in order to co-ordinate marketing, development, decision making, etc.

**Comment by mekkim** [comment]
1 & 3 done.  @humphd You should now have admin access to the GA4 account for EBSECan.

**Comment by humphd** [comment]
@mekkim excellent, thank you!  I'll work on 2 and submit a PR soon.
