### ISSUE TITLE
Summary page footer distorted

### ISSUE THREAD

**Issue by HaiderZaidiDev** [mekkim/donatemask#30]
Footer for the summary page's is higher than it should be, looks like it's being propped up by the Google Ad banner, for those with ad blocker, it looks like it's floating in the middle of the page. Attached screenshot demonstrating.

![image](https://user-images.githubusercontent.com/45272003/152458803-203aefe0-c00b-45f9-95a3-de9a623033ca.png)

**Comment by mekkim** [comment]
I've changed the ad settings to disable anchor ads (the one at the bottom) that is sometimes covering the footer.  However, I'm not sure it's related to what's happening with the footer floating.  Let's see if it is fixed.  It'll take about an hour for Google to change the Ad algorithm.

**Comment by mekkim** [comment]
Looks resolved in latest push.  Thanks!
