### ISSUE TITLE
When Clicking Submit on Request Page Redirect to Confirmation

### ISSUE THREAD

**Issue by mekkim** [mekkim/donatemask#31]
Major issue here is that it's not obvious if the request went through so people are clicking submit multiple times and creating multiple entries.
There needs to be a "on-submit" action that redirects them to a confirmation page.

**Comment by JessEBuchanan** [comment]
I finally had some time to work on this today, but I noticed we do have a message that appears after a request goes through. Not sure if that is new since I last pull/fetched but just want to check if we still want a full page redirect to confirm the request has gone through.

**Comment by mekkim** [comment]
Given that even with the new message popup we're still getting a lot of duplicate submissions (one person submitted 5 times in a row yesterday), yes, please, I'd still like a full redirect so that it's impossible to double-click the submit button accidentally, which still happens with the popup.

**Comment by JessEBuchanan** [comment]
Got it, should be close to done on it. Just having a little trouble getting it to actually go to the confirmation page :/

**Comment by Sync271** [comment]
Hey @JessEBuchanan , if you need any help just make a PR and just mention what you need help with.

**Comment by JessEBuchanan** [comment]
> Hey @JessEBuchanan , if you need any help just make a PR and just mention what you need help with.

Thanks, I might do that soon if I can't figure out this last piece. Between only finding a few hours here and there to work on it and learning as I go, progress is going slower than I had hoped :/

**Comment by JessEBuchanan** [comment]
New pull request to merge code to dev that will implement the confirmation page and redirect for mask requests.

**Comment by mekkim** [comment]
It's working! Gerat job, @JessEBuchanan!  Closing as complete.
