### ISSUE TITLE
Request Has Gone Through Confirmation Happens Even if Database Is Down

### ISSUE THREAD

**Issue by mekkim** [mekkim/donatemask#36]
While database was down recently, noticed that when submitting a request, the message "Thank you! Your request has been received!" pops up even though nothing was written to the database.  We should have an actual validation that the request made it to the database before confirming to the user.  This bug can be fixed when also adding a redirect to a thank you page on submit instead of keeping the user on the same page which is leading to the button being hit multiple times in error.

**Comment by Sync271** [comment]
Can I work on this? If yes, do you already have a "Thank You" page in mind? If not we can use the same pop up to just tell -"Something went wrong" or "Our Servers are Down for Maintainance"

**Comment by mekkim** [comment]
> Can I work on this? If yes, do you already have a "Thank You" page in mind? If not we can use the same pop up to just tell -"Something went wrong" or "Our Servers are Down for Maintenance"

Sure! Go right ahead.  There's a separate open issue for the thank you page which could be merged.  No specific design in mind.  Flexible!  Go nuts!
