### ISSUE TITLE
Buttons Sometimes Disappear When Clicking Between Pages

### ISSUE THREAD

**Issue by mekkim** [mekkim/donatemask#45]
Seems to have something to do with the rapid middle-frame only refresh of the website. It doesn't refresh all of the buttons so some of them are missing when clicking between sections of the site. Refreshing fixes it temporarily, but clicking between sections makes them disappear again.

**Comment by Sync271** [comment]
Hey @mekkim, can you give more context or post a screenshot that might help?

**Comment by mekkim** [comment]
Steps to reproduce (Chrome desktop, 98.0.4758.82 (Official Build) (64-bit)): Visit https://donatemask.ca -> Click "request" at the top toolbar -> Click "donate" at the top toolbar.  The icons won't load correctly per the screenshot attached.

![Screenshot](https://user-images.githubusercontent.com/9969062/153502128-c5502cf0-b1ce-4cce-8c8f-b34f9cc10faf.png)

**Comment by mekkim** [comment]
I came across the following blog post which might explain the problem: https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually

**Comment by mekkim** [comment]
Resolved by #67
