### ISSUE TITLE
Add Sponsors & Partners Page

### ISSUE THREAD

**Issue by mekkim** [mekkim/donatemask#52]
As we start receiving sponsorships/partnerships, we can add a page to showcase their logos.  Can be based on the about us page using a similar structure with logos instead of headshots and links to their online presences.

**Comment by Sync271** [comment]
If you can get me a list of sponsorships/partnerships, I can get started

**Comment by mekkim** [comment]
Current list (feel free to grab their logos/branding/social media/whatever from their public websites):

- [Desjardins](https://desjardins.com/)
- [Eclipse Innovations](https://eclipseinnovations.com/)
- [Vitacore](https://vitacore.ca/)
- [TTC](https://www.ttc.ca)
- [FDK Supply](fdksupply.com/)
