### ISSUE TITLE
Look Into Shopify Charity Donation Options

### ISSUE THREAD

**Issue by mekkim** [mekkim/donatemask#6]
Look into Shopify charity donation options and other integrations that might be useful for the Donate A Mask Project.

**Comment by yabenatti** [comment]
For the Non Profit Organization (NPO) discount, the org needs to be verified and a discount will be applied, but it has to be done through support:
https://www.shopify.ca/contact?utm_campaign=Guru+ASK&utm_medium=forum&utm_source=social

As for the payments, it does have Shopify Payments, but it requires one of the plans (in this case, it would be the NPO store front)
https://www.shopify.com/payments

Another payment option (beyond Stripe) is Klarna (a Swedish company), I don't know about their pricing, but it might offer competitive options.
https://www.klarna.com/se/

And this answer has some other links that are interesting, apps you can add to the store, etc
https://community.shopify.com/c/shopify-apps/shopify-for-non-profits/m-p/598513/highlight/true#M18741
