### ISSUE TITLE
Integrate Stripe Into Website

### ISSUE THREAD

**Issue by mekkim** [mekkim/donatemask#8]
Stripe account has been set up and 6 "products" (3 one-time and 3 monthly recurring) have been set up for 1, 10, and 20 "mask" donations respectively, at the $2.50CAD multiplier rate.  

Instructions on how to incorporate into the website [are here](https://support.stripe.com/questions/how-to-accept-donations-through-stripe)

**Comment by mekkim** [comment]
@HaiderZaidiDev and @devarsh19 have been given "Developer" access to the Stripe account using their @donatemask.ca email addresses.

**Comment by HaiderZaidiDev** [comment]
Closed in merge request, please see "stripe-integration" branch.
